language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
  - sudo apt-get install libboost-all-dev
script:
  - mkdir build && cd build && cmake .. && cmake --build . && make
