matrix:
  include:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
    - sudo tar -xzf boost_1_64_0.tar.gz
    - cd boost_1_64_0/
    - sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=log,program_options
    - sudo ./b2
    - sudo ./b2 install
  
language: cpp

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
script:
  - mkdir build && cd build && cmake .. && cmake --build . && make
